[package]
name = "jandan_pic_bot"
version = "0.1.0"
authors = ["iovxw <iovxw@outlook.com>"]

[dependencies]
error-chain = "0.7"
regex = "0.1"
curl = "0.3"
serde_json = "0.8"
telegram-bot = "0.4"
select = {git = "https://github.com/utkarshkukreti/select.rs"}